# spec_driven_model/tests/spec_poxsd_view.py
from odoo import fields, models
from odoo.addons.spec_driven_model.models import spec_models, spec_view


# --- Test SpecModel with View ---
class POXSDUsaddressView(spec_models.SpecModel, spec_view.SpecViewMixin):
    _name = "poxsd.10.usaddress.viewtest"  # Needs to be a concrete model for views
    _inherit = "poxsd.10.usaddress"  # Abstract spec mixin
    _description = "POXSD USAddress (View Test)"
    _auto = True  # Make it a real model

    # Example of view customization
    _poxsd10_view_field_settings = {
        "poxsd10_zip": {"widget": "char", "placeholder": "Enter ZIP"},
        "poxsd10_country": {"invisible": "1"},
    }

    def _get_spec_view_page_title(self, spec_prefix):
        if spec_prefix == "poxsd10":
            return "Address Details (Test)"
        return super()._get_spec_view_page_title(spec_prefix)


class POXSDCommentView(spec_models.SpecModel, spec_view.SpecViewMixin):
    _name = "poxsd.10.comment.viewtest"
    _inherit = "poxsd.10.comment"
    _description = "POXSD Comment (View Test)"
    _auto = True


# --- Test StackedModel with View ---
class POXSDPurchaseOrderTypeView(spec_models.StackedModel, spec_view.SpecViewMixin):
    _name = "poxsd.10.purchaseordertype.viewtest"
    _inherit = "poxsd.10.purchaseordertype"  # This is the stacking_mixin
    _description = "POXSD Purchase Order (Stacked View Test)"
    _auto = True

    # Configuration for StackedModel (from previous tests)
    # Ensure spec_prefix for _poxsd10_odoo_module matches the test setup
    _poxsd10_odoo_module = "odoo.addons.spec_driven_model.tests.spec_poxsd"
    _poxsd10_stacking_mixin = "poxsd.10.purchaseordertype"  # The root of stacking
    _poxsd10_stacking_points = {  # Manually define what's stacked FOR THIS TEST
        "poxsd10_items": None,  # Actual field object will be set by StackedModel
    }
    # We'll let poxsd10_shipTo and poxsd10_billTo be regular M2Os for this test

    # Fields that are part of poxsd.10.items (the stacked part)
    # These are "brought up" by StackedModel's inheritance magic.
    # We need them defined here if we expect them to be on this model directly.
    # Alternatively, _recursive_build_view_arch would look them up on the original abstract model.
    # For simplicity, let's assume StackedModel makes them available.
    poxsd10_item = fields.One2many(  # This comes from poxsd.10.items which is stacked
        "poxsd.10.item.viewtest",  # A concrete model for line items
        "purchase_order_id",  # Hypothetical inverse name
        string="POXSD Items (Line)",
    )

    # Customizations for the stacked view
    _poxsd10_view_field_settings = {
        "poxsd10_orderDate": {
            "attrs": "{'readonly': [('poxsd10_confirmDate', '!=', False)]}"
        },
    }

    def _get_spec_view_custom_xml_override(self, spec_prefix, path_str):
        if (
            spec_prefix == "poxsd10" and path_str == "purchaseordertype.items"
        ):  # Path of the items group
            return """
                <group string="Custom Items Section Override">
                    <field name="poxsd10_item" colspan="4" nolabel="1">
                        <tree>
                            <field name="poxsd10_productName"/>
                            <field name="poxsd10_quantity"/>
                        </tree>
                    </field>
                    <label string="This is a custom XML override for items!"/>
                </group>
            """
        return None


# Concrete model for purchase order lines (items)
class POXSDItemView(spec_models.SpecModel, spec_view.SpecViewMixin):
    _name = "poxsd.10.item.viewtest"
    _inherit = "poxsd.10.item"
    _description = "POXSD Item (Line View Test)"
    _auto = True

    purchase_order_id = fields.Many2one("poxsd.10.purchaseordertype.viewtest")

    _poxsd10_view_field_settings = {
        "poxsd10_USPrice": {
            "widget": "monetary",
            "options": "{'currency_field': 'currency_id'}",
        },
    }
    currency_id = fields.Many2one(
        "res.currency", default=lambda self: self.env.ref("base.EUR").id
    )


# Model to simulate one auto-generated by _register_hook
class AutoGeneratedSpecModel(spec_models.SpecModel, spec_view.SpecViewMixin):
    _name = "poxsd.10.autogen.test"  # This would normally be just 'poxsd.10.autogen'
    _inherit = "poxsd.10.usaddress"  # Inherit some fields for testing
    _description = "Auto-Generated Spec Model for View Test"
    _auto = True  # Normally True, but _register_hook does the setup.
    # For testing, we'll control its creation.
    _module = "spec_driven_model"  # Mock module

    # Mock _spec_prefix for _create_default_spec_views if called directly on class
    @classmethod
    def _spec_prefix(cls, split=False):
        return ("poxsd", "10") if split else "poxsd10"

    # Add a _rec_name for better default tree view
    _rec_name = "poxsd10_name"
