{
    "name": "nfe spec",
    "version": "16.0.2.0.1",
    "author": "Akretion, Odoo Community Association (OCA)",
    "license": "LGPL-3",
    "category": "Accounting",
    "summary": "NF-e abstract models generated by xsdata-odoo from the oficial xsd",
    "depends": ["base"],
    "installable": True,
    "application": False,
    "development_status": "Mature",
    "maintainers": ["rvalyi"],
    "website": "https://github.com/OCA/l10n-brazil",
}
